---
default_stages: [commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-yaml
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    sha: 1.11.0
    hooks:
    - id: shfmt
      args: [-i 2, -ci, -w]

